CREATE OR REPLACE PROCEDURE INSERT_CELEBRITY(
    FIRSTNAME IN VARCHAR2,
    LASTNAME IN VARCHAR2,
    STAGENAME IN VARCHAR2,
    GENDER IN VARCHAR2) AS
    BEGIN
        INSERT INTO CELEBRITY VALUES( NULL, FIRSTNAME, LASTNAME, STAGENAME, GENDER);
       COMMIT;
    END;
/
