CREATE USER CELEBRITY_DB IDENTIFIED BY p4ssw0rd;
GRANT CONNECT, RESOURCE TO CELEBRITY_DB;
GRANT DBA TO CELEBRITY_DB;
CREATE TABLE CELEBRITY(
C_ID NUMBER,
C_FIRST_NAME VARCHAR2(40),
C_LAST_NAME VARCHAR2(20),
C_STAGE_NAME VARCHAR2(40),
C_GENDER VARCHAR2(20),
PRIMARY KEY (C_ID)
);

--SEQUENCE USED TO AUTO INCREMENT
CREATE SEQUENCE CELEBRITY_SEQ
  START WITH 1
  INCREMENT BY 1;
--TRIGGER THAT WILL INCREMENT THE SEQUENCE
--AND ALTER THE PRIMARY KEY VALUE OF AN INSERT
CREATE OR REPLACE TRIGGER CELEBRITY_B_INSERT
BEFORE INSERT
ON CELEBRITY
FOR EACH ROW
BEGIN
  /* INCREASE THE SEQUENCE */
  --IF YOU DON'T WANT USERS TO INSERT ANY VALUE TO THE PK
  --COLUMN, REMOVE THE IF STATEMENT.
  IF :NEW.C_ID IS NULL THEN
    SELECT CELEBRITY_SEQ.NEXTVAL INTO :NEW.C_ID FROM DUAL;
  END IF;
END;
/
-- FORWARD SLASH
SELECT CELEBRITY_SEQ.NEXTVAL FROM DUAL;
DESCRIBE CELEBRITY;
INSERT INTO CELEBRITY 
VALUES(NULL,'Jim','Carrey',NULL,'M',NULL,NULL,1);
SELECT MAX(C_ID) FROM CELEBRITY;